name: Deploy to Heroku
on:
  push:
    branches: [master]
jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_APIKEY }}
        heroku_app_name: "tranquil-springs-39935"
        heroku_email: "lenny.cipondoh@gmail.com"